### ISSUE TITLE
partial fit resets random state

### ISSUE THREAD

**Issue by mheilman** [civisanalytics/muffnn#15]
`partial_fit` resets the random state for shuffling minibatches [https://github.com/civisanalytics/muffnn/blob/master/muffnn/mlp/base.py#L84]

There should probably be a private random state attribute on the class that gets set only when fitting or partial fitting the first time.

Thanks to @beckermr for catching this.

**Comment by mheilman** [comment]
@beckermr, any further comments?  I just took a glance at it.  Sorry I didn't catch it earlier.  I think this is my bug originally.

**Comment by beckermr** [comment]
No comments from me.
