### ISSUE TITLE
pypi/conda hosting

### ISSUE THREAD

**Issue by mheilman** [civisanalytics/muffnn#19]
It'd be nice to host this package on pypi (and/or conda forge?).

I'm not sure if there's anything in particular we need to do about the TensorFlow dependency.  It looks like pypi has an [up-to-date version of TF](https://pypi.python.org/pypi/tensorflow).

However, it's not clear whether that provides GPU support.  There's also [this](https://pypi.python.org/pypi/tensorflow-gpu/0.12.0rc0), but that looks like it just has a Windows wheel at the moment...

**Comment by beckermr** [comment]
I think we should go for a pip package now even though there might be some issues with TF support. For most users, this is good enough and if they need to do GPU things, they probably know how to set things up anyways.

**Comment by beckermr** [comment]
Also, looks like they have a gpu specific pypy package now

https://pypi.python.org/pypi/tensorflow-gpu

**Comment by beckermr** [comment]
@mheilman ping on this one. thoughts?

**Comment by mheilman** [comment]
making a pypi package seems like a good idea

**Comment by beckermr** [comment]
Mmmmk. I will try and take a first pass at this, but I am a pypi package noob.

**Comment by beckermr** [comment]
Maybe we should push the version we have to pip before upgrading TF in #30? Might be good for dependencies etc.

**Comment by beckermr** [comment]
Done. https://pypi.python.org/pypi?name=muffnn&version=0.2.0&:action=display
