### ISSUE TITLE
can't grid search over solver_kwargs

### ISSUE THREAD

**Issue by mheilman** [civisanalytics/muffnn#42]
One can't grid search over `solver__kwargs` in the MLP estimators because `get_params` can't find them.

```
from sklearn.datasets import load_digits
from muffnn import MLPClassifier
from sklearn.model_selection import GridSearchCV

digits = load_digits()
gs = GridSearchCV(MLPClassifier(), param_grid={'solver_kwargs': [{'learning_rate': x} for x in [0.1, 1.0, 10.0]]})
gs.fit(digits.data, digits.target)
```

This results in this exception:

```
ValueError: Invalid parameter solver_kwargs for estimator MLPClassifier. Check the list of available parameters with `estimator.get_params().keys()`.
```

I think we should just remove the `**` [here](https://github.com/civisanalytics/muffnn/blob/8963d73d1712afa908c472b50071f3711f674b2b/muffnn/mlp/mlp_classifier.py#L58) (and similarly in the other classes).

**Comment by beckermr** [comment]
Ahhh yes. This is my bad. 😦
