### ISSUE TITLE
muffnn version on pip is not up to date with all commits  

### ISSUE THREAD

**Issue by samcarlos** [civisanalytics/muffnn#73]
[rabble rabble](https://www.youtube.com/watch?v=9gSQg1i_q2g)

**Comment by denver1117** [comment]
seriously this is a big blocker!

**Comment by Mikelew88** [comment]
🍿

**Comment by beckermr** [comment]
OMG. https://pip.pypa.io/en/stable/reference/pip_install/#vcs-support

J/K @samcarlos 

We need to cut a new version. :)

**Comment by beckermr** [comment]
Though that will work in a pinch.

**Comment by samcarlos** [comment]
Haha. Thanks @beckermr !

**Comment by beckermr** [comment]
This has now been pushed to pypi! Happy muffnning!

**Comment by samcarlos** [comment]
gonna bake some nice muffnns :). Thanks!
